name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.3
  permission_handler: ^11.3.1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.2
  webview_flutter_wkwebview: ^3.13.1
  json_annotation: ^4.10.0
  go_router: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  json_serializable: ^6.12.0
  build_runner: ^2.11.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
